version: '3'
services:
  frontend:
    container_name: frontend
    image: ericknbaraujo/snowee-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
